name: terminator
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - h5py=3.6.0
  - matplotlib=3.5.1
  - scikit-learn=1.0.2
  - pytorch
  - torchvision
  - plotly=5.6.0
  - pip=21.2.4
  - pip:
    - hydra-core==1.2.0
    - wandb==0.12.17
    - datasets==2.2.2
    - pytorch-lightning==1.6.4
    - torchmetrics==0.9.0
    - torch_optimizer
    - einops
    - spikingjelly
