name: terminator
channels:
  - pytorch
  - defaults
dependencies:
  - python==3.11
  - pytorch==2.3.1
  - torchvision==0.18.1
  - pip:
    - datasets==2.20.0
    - torchmetrics==0.9.0
    - transformers==4.42.3
